version: '3.8'
services:
  bot:
    build: .
    container_name: docbot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./database:/app/database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped 