version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  doc_checker_bot:
    build: .
    container_name: doc_checker_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
volumes:
  ollama_data: 